import type { Metadata } from 'next'
import './globals.css'
import { Bodoni_Moda } from 'next/font/google'


const bodoniModa = Bodoni_Moda({
  subsets: ['latin'],        // Specify subsets (e.g., latin, latin-ext)
  weight: ['400', '700'],    // Specify font weights you need
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={bodoniModa.className}>{children}</body>
    </html>
  )
}
